#!/bin/bash
#!/bin/bash

# Set source and destination directories
src_dir=$(pwd)
dest_dir=$(dirname "$src_dir")

# Copy HTML files to parent directory if they are newer or do not exist
for file in "$src_dir"/*.html; do
    if [ -f "$dest_dir/$(basename "$file")" ] && [ "$file" -ot "$dest_dir/$(basename "$file")" ]; then
        echo "Skipping $file - file already exists in $dest_dir and is newer"
    else
        cp "$file" "$dest_dir"
        echo "Copied $file to $dest_dir"
    fi
done
